---
name: Patrick
surname: Sadil
position: "Postdoctoral Research Fellow"
address: "Johns Hopkins Bloomberg School of Public Health; Biostatistics"
www: psadil.github.io/psadil
email: "psadil1@jh.edu"
github: psadil
linkedin: psadil
orcid: 0000-0003-4141-1343
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
csl: ../csl/apa-cv.csl 
headcolor: 414141 # use black color
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(readr)
```

# Education

```{r education}
read_csv(
  here::here("data", "education.csv"),
  col_types = cols(
    degree = col_character(),
    start_date = col_double(),
    end_date = col_double(),
    institution = col_character(),
    where = col_character())) %>%
  detailed_entries(
    what = institution,
    when = glue::glue("{start_date}--{end_date}"),
    with = degree,
    where = where)
```

# Publications

## Preprints

```{r preprints}
bibliography_entries(here::here("data", "preprints.bib"))
```

## Peer-Reviewed

```{r publications}
bibliography_entries(here::here("data", "publications.bib"))
```

# Grants and Awards

```{r, grants}
read_csv(
  here::here("data", "grants.csv"),
  col_types = cols(
    name = col_character(),
    when = col_double(),
    with = col_character(),
    where = col_character(),
    amount = col_character(),
    why = col_character())) %>% 
  detailed_entries(
    what = amount,
    when = when,
    with = name,
    where = where,
    why = why)
```

# Presentations

```{r, presentations}
bibliography_entries(here::here("data", "presentations.bib"))
```


# Peer Review


```{r review}

tibble::tribble(
  ~ what, ~ details,
  "Ad hoc book review", c("Springer"), 
  "Ad hoc review for journals", c("Journal of Mathematical Psychology")) %>%
  detailed_entries(why = details, what = what)

```


# Workshops Attended

```{r, workshops}
read_csv(
  here::here("data", "workshops.csv"),
  col_types = cols(
    what = col_character(),
    when = col_double(),
    where = col_character())) %>% 
  brief_entries(
    what = what,
    when = when,
    with = where)
```


