---
name: Patrick
surname: Sadil
position: "Postdoctoral Research Fellow"
address: "Johns Hopkins Bloomberg School of Public Health; Biostatistics"
www: psadil.github.io/psadil
email: "psadil1@jh.edu"
github: psadil
linkedin: psadil
orcid: 0000-0003-4141-1343
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
csl: ../csl/apa-cv.csl 
headcolor: 414141 # use black color
docname: Résumé
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(readr)
```

# Education

```{r education}
education <- read_csv(
  here::here("data", "education.csv"),
  col_types = cols(
    degree = col_character(),
    start_date = col_double(),
    end_date = col_double(),
    institution = col_character(),
    where = col_character())) %>%
  dplyr::rowwise() %>%
  dplyr::mutate(
    dplyr::across(tidyselect::starts_with("why"), ~ifelse(is.na(.x), list(), list(.x))),
    why = list(dplyr::c_across(tidyselect::starts_with("why"))))

education %>%
  detailed_entries(
    what = institution,
    when = glue::glue("{start_date}--{end_date}"),
    with = degree,
    why = why)

```

# Experience

```{r, experience}
tibble::tribble(
  ~ what, ~ date, ~ with, ~ details,
  "Johns Hopkins Bloomberg School of Public Health", "July 2021 - Present", "Postdoctoral Research Fellow - Biostatistics", c("Built quality control procedure for large neuroimaging dataset of chronic pain", "Arranged python and bash analysis pipeline at High Performance Computing center to automate data processing."),
  "University of Massachusetts, Amherst", "Sep 2020 - June 2021", "Postdoctoral Research Associate - Cognitive Psychology", c("Implemented user-friendly R package for inferring neuromodulation and bundle as BIDS Application", "Automated testing of package on multiple operating systems (Linux, macOS, Windows) with GitHub Actions", "Designed multi-day workshops on neuromodulation package, including background in Bayesian analyses"),
  "University of Massachusetts, Amherst", "Summer 2016 - Summer 2020", "Research Assistant", c("Organized tutorials and a weekly 'coding club' focused on software for graduate students", "Conducted research for and published two first-author papers under NSF and NIH funded projects"),
    "University of Massachusetts, Amherst", "Spring 2016", "Teaching Assistant - Research Methods in Psychology", c("Lectured to 20 psychology undergraduate students twice weekly, guiding students through three research projects", "Reviewed theory of introductory statistics, including lab-based practice", "Maintained office hours to review course content and exams one-on-one")) %>%
  detailed_entries(what = what, when = date, with = with, why = details)
```

# Personal Projects

```{r, projects}
tibble::tribble(
  ~ with, ~ details, ~ what,
    "\\$50000 grant from Oracle - Probing Bias in Automated Diagnoses from Medical Imaging", c("Ongoing project to study biases in predictions of health outcomes with the largest neuroimaging dataset ever collected", "Train machine and deep learning algorithms on one demographic, assess generalizability in others", "Running python scripts on Oracle Cloud Infrastructure"), NA_character_,
  "Machine Learning with Generative Adversarial Network", c("Scrapped ~25,000 images from Google Maps using Google APIs and python", "Preprocessed images in python for training TensorFlow neural network (stylegan2-ada)", "Trained network on Google Cloud Compute Engine"), NA_character_,
    "Online behavioral experiment", c("Prepared for COVID-19 by porting behavioral experiment to Heroku using python web framework (Django), Angular, and postgreSQL"), NA_character_) |>
  detailed_entries(with = what, why = details, what = with, .protect = FALSE)
```


