on:
  push:
    branches:
      - main

name: knit

jobs:
  knit:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      LANG: en_US.UTF-8
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-tinytex@v2

      - uses: r-lib/actions/setup-renv@v2

      - name: knit
        shell: Rscript {0}
        run: |
          tinytex::tlmgr_install("pdfcrop")
          rmarkdown::render(
            here::here("cv", "cv.Rmd"),
            quiet=TRUE,
            output_dir = here::here(),
            output_file = "tmp")
          rmarkdown::render(
            here::here("resume", "resume_psadil.Rmd"),
            quiet=TRUE,
            output_dir = here::here(),
            output_file = "resume_psadil")

      - name: commit cv
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git fetch origin gh-pages
          git checkout gh-pages
          mv tmp.pdf cv.pdf
          git commit -m "generated pdfs"
          git push origin gh-pages

