on:
  push:
    branches:
      - main

name: knit

jobs:
  knit:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      LANG: en_US.UTF-8
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.3'

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-tinytex@v1

      - name: cache r packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: install packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: knit
        shell: Rscript {0}
        run: |
          rmarkdown::render(
            here::here("cv", "cv.Rmd"),
            quiet=TRUE,
            output_dir = here::here(),
            output_file = "tmp")

      - name: commit cv
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git fetch origin gh-pages
          git checkout gh-pages
          mv tmp.pdf cv.pdf
          git add cv.pdf
          git commit -m "generated cv"
          git push origin gh-pages

